language: objective-c
osx_image: xcode8
before_install:
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
install: script/update
script: 
  - xcodebuild -version
  - xcodebuild -showsdks
  - script/test
